name: Build and Test
run-name: Build and Test ${{ github.actor }} ${{ github.event_name }}

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The runner environment for the job (e.g., ubuntu-latest, windows-latest).'
        required: false
        type: string
        default: 'ubuntu-latest'

      ref:
        description: 'The Git ref to checkout.'
        required: true
        type: string

      upload-coverage:
        description: 'Whether to upload the code coverage report (only runs on ubuntu-latest).'
        required: false
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      runs-on:
        description: 'The runner environment for the job (e.g., ubuntu-latest, windows-latest).'
        required: false
        type: string
        default: 'ubuntu-latest'

      ref:
        description: 'The Git ref to checkout.'
        required: true
        type: string

      upload-coverage:
        description: 'Whether to upload the code coverage report (only runs on ubuntu-latest).'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  get-configs:
    uses: ./.github/workflows/configs.yml

  build-test-nodejs:
    needs: [ get-configs ]
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      code-quality: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          fetch-tags: true

      - name: Git Status
        shell: bash
        run: echo "Building from branch=$(git rev-parse --abbrev-ref HEAD), commit=$(git rev-parse HEAD), tag=$(git describe --tags --exact-match)"

      - name: Setup Node.js ${{ needs.get-configs.outputs.node-version }} (${{ runner.os }})
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.get-configs.outputs.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Code Quality
        run: npm run lint && npm run check:duplicates

      - name: Test
        run: npm run test

      - name: Upload coverage report
        if: inputs.upload-coverage && inputs.runs-on == 'ubuntu-latest'
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage/cobertura-coverage.xml
          language: TypeScript
          label: code-coverage/vitest
