name: App Configs

on:
  workflow_call:
    outputs:
      node-version:
        description: "Node.js version"
        value: ${{ jobs.get-versions.outputs.node-version }}

permissions:
  contents: read

jobs:
  get-versions:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '24.x'
    outputs:
      node-version: ${{ env.NODE_VERSION }}
    steps:
      - name: Provide Versions
        run: |
          echo "Exporting Node.js version = ${{ env.NODE_VERSION }}"
