name: Release
run-name: Release ${{ inputs.tag }} ${{ github.actor }} ${{ github.event_name }}

on:
  workflow_call:
    inputs:
      tag:
        description: "The tag to release (1.0.0-beta, 1.0.0)"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release (1.0.0-beta, 1.0.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  get-configs:
    uses: ./.github/workflows/configs.yml

  version-and-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag: ${{ steps.validate-tag.outputs.tag }}
      is-prerelease: ${{ steps.validate-tag.outputs.is-prerelease }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.tag }}
          fetch-tags: true

      - name: Get version from package.json
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Validate tag matches version
        id: validate-tag
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          TAG=${{ inputs.tag }}
          
          if [[ "$TAG" == "$VERSION" ]]; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "is-prerelease=false" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == "$VERSION-beta" ]]; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "is-prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "Error: Tag ($TAG) must be $VERSION or $VERSION-beta"
            exit 1
          fi

  build-and-test:
    needs: [ get-configs, version-and-tag ]
    permissions:
      contents: read
      code-quality: write
    uses: ./.github/workflows/build-and-test.yml
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    with:
      ref: ${{ needs.version-and-tag.outputs.tag }}
      runs-on: ${{ matrix.os }}

  bundle:
    needs: [ get-configs, version-and-tag, build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.version-and-tag.outputs.tag }}
          fetch-tags: true

      - name: Git Status
        shell: bash
        run: echo "Bundling from branch=$(git rev-parse --abbrev-ref HEAD), commit=$(git rev-parse HEAD), tag=$(git describe --tags --exact-match)"

      - name: Setup Node.js ${{ needs.get-configs.outputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.get-configs.outputs.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Bundle (${{ needs.get-configs.outputs.node-version }})
        shell: bash
        run: |
          TAG=${{ needs.version-and-tag.outputs.tag }}
          if [[ "$TAG" =~ -beta$ ]]; then
            npm run bundle:beta
          else
            npm run bundle:prod
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: vsix
          path: '*.vsix'
          if-no-files-found: error
          retention-days: 1

  release:
    needs: [ version-and-tag, bundle ]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: vsix
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.version-and-tag.outputs.tag }}
          prerelease: ${{ needs.version-and-tag.outputs.is-prerelease }}
          files: artifacts/*.vsix
          generate_release_notes: true
          fail_on_unmatched_files: true
